name: Deploy Angular to GitHub Pages

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installer Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      # 3. Installer dépendances
      - name: Install dependencies
        run: npm install

      # 4. Build Angular
      - name: Build project
        run: npm run build -- --base-href "/portfolio/"

      # 5. Upload build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/portfolio/browser

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
